"Indent settings
set autoindent
set tabstop=4
set shiftwidth=4
set smarttab
set expandtab

set autochdir

"Search settings
set hlsearch    "Highlight all search results
set smartcase   "Enable smart-case search
set ignorecase  "Always case-insensitive
set incsearch   "Searches for strings incrementally

"Hidden characters
set listchars=eol:$,tab:->,trail:~,extends:>,precedes:<,space:·
set list

"Vertical line
if exists('+colorcolumn')
    set colorcolumn=80
else
    au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
endif

"Plugins management
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'morhetz/gruvbox'
Plug 'airblade/vim-gitgutter'
Plug 'kien/ctrlp.vim'
Plug 'tpope/vim-surround'

Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'w0rp/ale'
Plug 'elzr/vim-json'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

call plug#end()

"NerdTree config
:let g:NERDTreeWinSize=40
let NERDTreeShowHidden=1
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * call s:turnNerdTree(argc())

function! s:turnNerdTree(argc)
    if a:argc == 0 && !exists("s:std_in")
        NERDTree
    endif
endfunction


"Appereance
set ruler
set number
syntax on
set t_Co=256
set background=dark
colorscheme gruvbox

"Keys mapping
map <C-n> :NERDTreeToggle<CR>
map - ddp
map _ ddkP

imap <c-w> <esc>:w<cr>i
imap <c-e> <esc>$i
imap <c-z> <esc>ui

